#Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'LinkMo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
  target 'ShareLink' do
  # Pods for LinkMo
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
    pod 'RxDataSources', '~> 4.0'
    pod 'SnapKit', '~> 5.0.0'
    pod 'NeumorphismKit', '~> 0.2'
    pod 'EMTNeumorphicView'
  end

end
